name: wasteagram
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  location: ^3.0.0
  image_picker: ^0.6.7
  cloud_firestore:
  firebase_core:
  firebase_storage: ^6.0.0
  intl: ^0.16.0
  firebase_analytics: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
